// WARNING!
// LINES BELOW ARE IGNORED IN THE PRODUCTION ENV IF IT IS TAGGED WITH THE COMMENT: /*DEV*/
[
  'biruni/externals/underscore.js',
  'biruni/externals/string-prototype.js',
  'biruni/externals/number-prototype.js',
  'biruni/externals/user-agent-detecter.js',
  'biruni/externals/functions.js',

  'biruni/biruni-module.js',

  'biruni/biruni-template-loader.js',

  'biruni/constants/forms.js',
  'biruni/constants/langs.js',
  'biruni/constants/routes.js',
  'biruni/constants/assets.js',
  'biruni/constants/fonts.js',
  'biruni/constants/themes.js',
  'biruni/constants/constants.js',

  'biruni/filters/b-number.js',

  'biruni/factories/b-util.js',
  'biruni/factories/b-require.js',
  'biruni/factories/b-big.js',
  'biruni/factories/b-config.js',
  'biruni/factories/b-storage.js',
  'biruni/factories/b-http.js',
  'biruni/factories/b-alert.js',
  'biruni/factories/b-confirm.js',
  'biruni/factories/b-grid-filter.js',
  'biruni/factories/b-pg-grid-filter.js',
  'biruni/factories/b-sort-form.js',
  'biruni/factories/b-query.js',
  'biruni/factories/b-grid.js',
  'biruni/factories/b-grid-scroll.js',
  'biruni/factories/b-pg-grid.js',
  'biruni/factories/b-base-page.js',
  'biruni/factories/b-page.js',
  'biruni/factories/b-subpage.js',
  'biruni/factories/b-frame.js',
  'biruni/factories/b-hotkey.js',
  'biruni/factories/b-preview.js',
  'biruni/factories/b-face-cropper.js',
  'biruni/factories/b-content-maker.js',
  'biruni/factories/b-session-storage.js',

  'biruni/directives/b-number.js',
  'biruni/directives/b-inputmask.js',
  'biruni/directives/b-telinput.js',
  'biruni/directives/b-date-picker.js',
  'biruni/directives/b-date-range-picker.js',
  'biruni/directives/b-page.js',
  'biruni/directives/b-subpage.js',
  'biruni/directives/b-grid/b-grid.js',
  'biruni/directives/b-grid/b-col.js',
  'biruni/directives/b-grid/b-action.js',
  'biruni/directives/b-grid-filter/b-grid-filter.js',
  'biruni/directives/b-grid-filter-panel/b-grid-filter-panel.js',
  'biruni/directives/b-grid-controller/b-grid-controller.js',
  'biruni/directives/b-scrollable.js',
  'biruni/directives/b-qlikpage.js',
  'biruni/directives/b-when-scrolled.js',
  'biruni/directives/b-r.js',
  'biruni/directives/b-t.js',
  /*DEV*/ 'biruni/directives/b-tdev/b-tdev.js',
  'biruni/directives/b-map.js',
  'biruni/directives/b-maxlength.js',
  'biruni/directives/b-editor/b-editor.js',
  'biruni/directives/b-pagination.js',
  'biruni/directives/b-input/b-input.js',
  'biruni/directives/b-toggle.js',
  'biruni/directives/b-tree-select/b-tree-select.js',
  'biruni/directives/b-pg-grid.js',
  'biruni/directives/b-pg-controller/b-pg-controller.js',
  'biruni/directives/b-dropzone/b-dropzone.js',
  'biruni/directives/b-cropper/b-cropper.js',
  'biruni/directives/b-validate.js',
  'biruni/directives/b-hotkey.js',
  'biruni/directives/b-offcanvas/b-offcanvas.js',
  'biruni/directives/b-content-maker/b-content-maker.js',
  'biruni/directives/b-dynamic-field/b-dynamic-field.js',

  'biruni/directives/ui-select.js',

  'app-onload.js',
  'app-module.js',
  'app-config.js',
  'app-hotkey.js',
  'app-socket.js',
  'app-setting.js',
  'app-session-timer.js',
  'app-session.js',
  'app-search.js',
  'app-feedback.js',
  'app-ctrl.js',
  /*DEV*/ 'app-dev.js',
  'app-bootstrap.js'
].forEach(function (src) {
  src = 'biruni/app/' + src;
  var script = document.createElement('script');
  script.src = src;
  script.async = false;
  document.head.appendChild(script);
});
