biruni.constant('bLangs', {
  FILIALS                  : 'Filials',
  PROJECTS                 : 'Projects',
  SEARCH_FILIAL            : 'Search filial',
  PROFILE                  : 'Profile',
  CHANGE_PASSWORD          : 'Change password',
  LOGOUT                   : 'Logout',
  LOGOUT_AND_FORGET        : 'Logout and forget',
  CLOSE                    : 'Close',
  YES                      : 'Yes',
  NO                       : 'No',
  NO_DATA_FOUND            : 'No data found',
  ERROR                    : 'Error',
  UNAUTHORIZED             : 'Unauthorized access',
  SEARCH_FOR               : 'Search for ...',
  CONFIRM_LOGOUT           : 'Do you want to log out?',
  CONFIRM_LOGOUT_AND_FORGET: 'Do you want to log out and forget?',
  CANCEL                   : 'Cancel',
  SORT                     : 'Sort',
  SORT_OFF                 : 'Switched off',
  SORT_ASCENDING           : 'Ascending',
  SORT_DESCENDING          : 'Descending',
  SORT_PIN                 : 'Pin as default',
  GRID_SETTING             : 'Grid setting',
  GRID_NO_RESULTS          : 'No data available',
  EXPORT_EXCEL             : 'Export excel',
  USER                     : 'User name',
  PASSWORD                 : 'Password',
  PASSWORD_IS_INCORRECT    : 'Password is incorrect',
  SIGN_IN                  : 'Sign in',
  NOT_YOU                  : 'Not you',
  INPUT_SELECTED           : 'selected items',
  INPUT_LOADING            : 'Loading',
  INPUT_PLACEHOLDER        : 'Search',
  INPUT_MORE               : 'Show more',
  INPUT_NO_DATA            : 'no data found',
  INPUT_ADD                : 'Add',
  INPUT_VIEW               : 'View',
  INPUT_SAVE_PIN_VALUE     : 'Save to default',
  INPUT_REMOVE_PIN_VALUE   : 'Remove default value',
  TREE_ADD                 : 'Add',
  TREE_VIEW                : 'View',
  TREE_MORE                : 'Show more',
  DR_TODAY                 : 'Today',
  DR_YESTERDAY             : 'Yesterday',
  DR_LAST_7_DAYS           : 'Last 7 Days',
  DR_FIRST_HALF_MONTH      : 'First Half-Month',
  DR_SECOND_HALF_MONTH     : 'Second Half-Month',
  DR_LAST_30_DAYS          : 'Last 30 Days',
  DR_THIS_MONTH            : 'This Month',
  DR_LAST_MONTH            : 'Last Month',
  DR_CUSTOM_RANGE          : 'Custom Range',
  DR_APPLY                 : 'Apply',
  DR_CANCEL                : 'Cancel',
  TOGGLE_FULL_SCREEN       : 'Toggle full-screen',
  FILE_MANAGER             : 'File manager',
  SET_DEFAULT              : 'Set default field',
  RESET_TO_DEFAULT         : 'Reset to default?',
  APPLY                    : 'Apply',
  GF_ADD_FILTER_FIELD      : 'Add filter field',
  GF_EQUAL                 : 'Equal',
  GF_FILTER_TITLE          : 'Filter title',
  GF_GREATER_THAN          : 'Greater than',
  GF_GREATER_THAN_EQUAL    : 'Greater than equal',
  GF_INPUT_FILTER          : 'Input filter name',
  GF_LESS_THAN             : 'Less than',
  GF_LESS_THAN_EQUAL       : 'Less than equal',
  GF_NEW_TEMPLATE          : 'New template',
  GF_NO_FILTERS            : 'No filters',
  GF_NOT_EQUAL             : 'Not equal',
  GF_NOT_SEARCH            : 'Not search',
  GF_SAVE_TEMPLATE         : 'Save template',
  GF_SEARCH                : 'Search',
  GF_SELECT_ALL            : 'select all',
  GF_SHOW_ALL              : 'Show all',
  GF_TEMPLATE              : 'Template',
  GF_UNKNOWN               : 'Unknown filter',
  GF_UNSELECT_ALL          : 'unselect all',
  GF_INCLUDE_NULLS         : 'Include nulls',
  GF_INCLUDE_NOT_NULLS     : 'Include not nulls',
  NT_SHOW_ALL              : 'Show all',
  SESSION_STAY             : 'Session stay',
  SESSION_EXPIRED          : 'Your session is about to expired',
  SESSION_REDIRECTION      : 'Redirection',
  SESSION_SECONDS          : 'seconds',
  SESSION_TIMEOUT          : 'Session timeout',
  SESSION_TIMEOUT_TITLE    : 'Session timeout notification',
  SESSION_LEFT             : 'seconds left',
  LOCK_SCREEN              : 'Lock Screen',
  PREF_CLEAR               : 'Preferences clear',
  DZ_DROP_FILE             : 'Drop file here or click the field',
  CRP_SAVE                 : 'Save',
  CRP_CLOSE                : 'Close',
  CRP_PREVIEW              : 'Preview',
  TS_CHECK_ALL             : 'Check all',
  TS_UNCHECK_ALL           : 'Uncheck all',
  TM_NOTIFICATIONS         : 'Notifications',
  TM_MESSAGES              : 'Messages',
  TM_QUICK_ACTIONS         : 'Quick actions',
  ST_SETTINGS              : 'Settings',
  ST_DOCUMENTATION         : 'Documentation',
  ST_CHAT                  : 'Chat',
  QA_CREATE_TASK           : 'Create new task',
  QA_ALL_TASKS             : 'All tasks',
  QS_GENERAL_SETTINGS      : 'General settings',
  QS_VIEW_SETTINGS         : 'Viewing settings',
  QS_SETTINGS              : 'Settings',
  QS_MESSAGES              : 'Messages',
  GS_APP_FONT              : 'App main font',
  GS_BACKGROUND            : 'Background',
  GS_INIT_FILIAL           : 'Filial',
  GS_INIT_FORM             : 'Form',
  GS_INIT_PROJECT          : 'Project',
  GS_MAIN_THEME            : 'Main theme',
  GS_SK_DASHBOARD          : 'Dashboard',
  GS_SK_SET_PARAMETERS     : 'Set parameters',
  GS_START_KIND            : 'Start work with',
  SH_ADD_TASK_CURRENT_FORM : 'Add task for this form',
  SH_SET_ACCESS            : 'Set access to roles',
  SH_ACCESS_REQUEST        : 'Send access request',
  SH_CUSTOM_TRANSLATE      : 'Custom translate',
  SH_OPEN_HELP             : 'Open help',
  SH_ADD_FAVORITE          : 'Add to favorite',
  SH_REMOVE_FAVORITE       : 'Remove from favorite',
  SH_SHOW_TOUR             : 'Show tour',
  SELECT_DATE              : 'Select date',
  PV_NOT_SUPPORT_VIDEO     : 'Your browser does not support the video tag',
  PV_UNAVAILABLE           : 'Unavailable',
  PV_DOWNLOAD              : 'Download',
  PV_UNABLE_TO_PREVIEW     : 'This file cannot be previewed',
  UPLOAD_FILE_CHANGED      : 'Uploaded file changed',
  CM_DATA                  : 'Data',
  CM_WORKSPACE             : 'Workspace',
  CM_PREVIEW               : 'Preview',
  CM_RUN                   : 'Run',
  CM_RUN_TO_NEW_TAB        : 'Run to new tab',
  CM_HELP                  : 'Help',
  CM_DOWNLOAD_AS_PDF       : 'Download as pdf',
  TB_BARCODE_SCANNER       : 'Barcode scanner',
  TB_BARCODE_HINT          : 'Scan the barcode to find the object',
  TB_BARCODE_NO_RESULT     : 'Nothing found',
  SEARCH                   : 'Search',
  SB_SEARCH_QUERY          : 'Search query',
  SB_RESULT_ALL            : 'All',
  SB_RESULT_FORMS          : 'Forms',
  SB_NO_RESULTS            : 'Nothing found.',
  SB_SHOW_MORE             : 'show more',
  SB_NOT_SPECIFIED         : 'not specified',
  ER_HEAD_SETTING          : 'Head setting',
  ER_FILIAL_SETTING        : 'Filial setting',
  MAP_GROUPING             : 'Group markers',
  ALERT_SOLUTIONS          : 'Solutions',
  ALERT_RECOMMENDED        : 'Recommended actions',
  FB_SEND_FEEDBACK         : 'Send feedback',
  FB_RATE_US               : 'Please rate us',
  FB_MAKE_ANONYMOUS        : 'Make anonymous',
  FB_ANONYMOUS             : 'Anonymous',
  FB_FEEDBACK_TYPE         : 'Feedback type',
  FB_FT_SUGGESTION         : 'Suggestion',
  FB_FT_COMMENT            : 'Comment',
  FB_NOTE                  : 'Note',
  FB_SEND                  : 'Send',
  FB_THANK_YOU             : 'Thank you for sending feedback',
  QLIK_NO_LICENSE          : 'No Qlik license',
  NEXT                     : 'Next',
  PREVIOUS                 : 'Previous',
  DONE                     : 'Done'
});
